# Generated by Django 3.2.6 on 2021-09-24 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram', models.CharField(max_length=200, null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('youtube', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'makers',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_code', models.CharField(max_length=50)),
                ('option_name', models.CharField(max_length=100)),
                ('used', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='MakerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.maker')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.option')),
            ],
            options={
                'db_table': 'maker_options',
            },
        ),
        migrations.AddField(
            model_name='maker',
            name='option',
            field=models.ManyToManyField(related_name='makers', through='makers.MakerOption', to='makers.Option'),
        ),
        migrations.AddField(
            model_name='maker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.maker')),
            ],
            options={
                'db_table': 'image_files',
            },
        ),
    ]
