# Generated by Django 3.2.6 on 2021-09-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
