# Generated by Django 3.2.6 on 2021-09-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0004_auto_20210927_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeroption',
            name='option_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
