# Generated by Django 3.2.6 on 2021-09-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0005_makeroption_option_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='id_image',
            field=models.ImageField(blank=True, default='camera.jpg', null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='maker',
            name='profile_image',
            field=models.ImageField(blank=True, default='camera.jpg', null=True, upload_to='image'),
        ),
    ]
