# Generated by Django 3.2.6 on 2021-09-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0007_auto_20210927_1533'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='licenseimage',
            table='license_images',
        ),
    ]
