# Generated by Django 3.2.6 on 2021-09-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0008_alter_licenseimage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeroption',
            name='option_name',
        ),
        migrations.AlterField(
            model_name='idimage',
            name='id_image',
            field=models.ImageField(blank=True, default='camera.png', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='licenseimage',
            name='license_image',
            field=models.ImageField(blank=True, default='camera.png', null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
            field=models.ImageField(blank=True, default='camera.png', null=True, upload_to='image'),
        ),
    ]
