# Generated by Django 3.2.6 on 2021-09-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0009_auto_20210927_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdImage',
            new_name='ImageFile',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='maker',
        ),
        migrations.RenameField(
            model_name='imagefile',
            old_name='id_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='makeroption',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='makers.option'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='imagefile',
            table='image_files',
        ),
        migrations.DeleteModel(
            name='LicenseImage',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
