# Generated by Django 3.2.6 on 2021-09-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0010_auto_20210927_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeroption',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='makers.option'),
        ),
    ]
